tools:
  nodejs: 16.13.2
  sonarscanner: 4.6.2.2472
  npm: 9.6.7

branches:
  - spec: main
    triggers:
      - pr:
          disabled: true
  - spec: release/*
    triggers:
      - push:
          call: ReleaseFlow
          call: run-sonar
      - manual:
          name: Make Release flow
          call: ReleaseFlow
      - pr:
          disabled: true
  - spec: stage
    triggers:
      - push:
          call: StageFlow
          call: run-sonar
      - manual:
          name: Make Stage flow
          call: StageFlow
      - pr:
          disabled: true
  - spec: develop
    triggers:
      - push:
          call: DevFlow
          call: run-sonar
      - manual:
          name: Make Dev flow
          call: DevFlow
      - pr:
          disabled: true
  - spec: feature/*
    triggers:
      - push:
          call: featureFlow
          call: run-sonar
      - manual:
          name: Make feature flow
          call: featureFlow
      - pr:
          disabled: true

flows:
  default:
    - echo "Starting default process"
  StageFlow:
    - echo "Starting stage process"
  DevFlow:
    - echo "Starting dev process"
  featureFlow:
    - echo "Starting feature process"
  ReleaseFlow:
    - echo "Starting release process"
  run-sonar:
    - (name [SONAR] - Sonar Scanner) sonar-scanner -Dproject.settings=sonar-project.properties
    - (name [HYGIEIA] - Publish Sonar) hygieia.publishSonar()